version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: yarn
      - run: yarn run prettier:check
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

workflows:
  version: 2
  build:
    jobs:
      - build
